CREATE TABLE IF NOT EXISTS followers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_uuid VARCHAR(255) NOT NULL,
    follower_uuid VARCHAR(255) NOT NULL,
    pending INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (user_uuid) REFERENCES users(uuid) ON DELETE CASCADE
);