CREATE TABLE IF NOT EXISTS comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    post_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    image TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);